const productos = [
    {id:"1", 
    descripcion: "El alimento de mejor calidad de la ciudad, bigotes contentos y bien alimentados", 
    nombre:"Alimento para gato", 
    precio:1550, 
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTo0g8eGxjj7CvakIVDcT9yAA8GPnP9NKN2KQ&usqp=CAU",
    category:"Gatos"},

    {id:"2", 
    descripcion: "El alimento de mejor calidad de la ciudad, meneo de cola incontrolable", 
    nombre:"Alimento para perro", 
    precio:1675, 
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqHVfUlFiBVU4kGe_MQhcvHy9wn8fnNXhbKg&usqp=CAU",
    category: "Perros"},

    {id:"3", 
    descripcion: "El alimento de mejor calidad de la ciudad, nadie mas feliz que ellos", 
    nombre:"Alimento para otros", 
    precio:1340, 
    imagen: "https://imagenes.elpais.com/resizer/e1rx6E_JsunOpj9xSKjdPmXzbck=/414x0/arc-anglerfish-eu-central-1-prod-prisa.s3.amazonaws.com/public/ZH2RRN5BI32FTUJ76NWUF25OEQ.jpg",
    category: "Otros"},

    {id:"4", 
    descripcion: "La cola y los bigotes mas limpios del condado", 
    nombre:"Baños", 
    precio:1075, 
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZAPMcd1wvI3UtpHkGfbBbuIuMhkq998sGSQ&usqp=CAU",
    category:"Perros"},

    {id:"5", 
    descripcion: "Vacunación, chequeos, malestares", 
    nombre:"Servicio veterinaria para perros", 
    precio:2370, 
    imagen: "https://imagenes.20minutos.es/files/image_656_370/files/fp/uploads/imagenes/2017/06/01/125505.r_d.300-169.jpg",
    category:"Perros"},

    {id:"6", 
    descripcion: "Vacunación, chequeos, malestares", 
    nombre:"Servicio veterinaria para gatos", 
    precio:1520, 
    imagen: "https://www.zooplus.es/magazine/wp-content/uploads/2017/11/katzenbaby-erstes-Besuch-beim-Tierarzt-1024x682.jpg",
    category:"Gatos"},

    {id:"7", 
    descripcion: "Vacunación, chequeos, malestares", 
    nombre:"Servicio veterinaria para otras mascotas", 
    precio:890, 
    imagen: "https://www.centroveterinariobarbanza.es/cuidados_img8829t1.jpg",
    category:"Otros"},

    {id:"8", 
    descripcion: "Los premios mas ricos, asi se aprende mejor!", 
    nombre:"Premios", 
    precio:550, 
    imagen:"https://i1.wp.com/pawsomedoglife.com/wp-content/uploads/2019/08/Pawsome-BLog-Premios-Caseros-Calabaza.jpg?fit=700%2C900&ssl=1",
    category:"Perros"},

    {id:"9", 
    descripcion: "¿Qué incluye? Selección de 7 productos adaptados al tamaño de tu mascota. Una caja con pelotas interactivas, juguetes temáticos, golosinas masticables, huesos, snacks 100% naturales, productos de higiene. ¡Generamos una experiencia única en cada compra!", 
    nombre:"Juguetes para perros", 
    precio:1950, 
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgs9XfTSdDAA1vYEz7dq4FoQ-aAAFQ-oW5AA&usqp=CAU",
    category: "Perros"},

    {id:"10", 
    descripcion: "¿Qué incluye? Selección de 7 productos adaptados al tamaño de tu mascota. Una caja con pelotas interactivas, juguetes temáticos, golosinas masticables, huesos, snacks 100% naturales, productos de higiene. ¡Generamos una experiencia única en cada compra!", 
    nombre:"Juguetes para gatos", 
    precio:1950, 
    imagen: "https://soyungato.com/wp-content/uploads/2020/05/gato-jugando-con-un-mordedor.jpg",
    category: "Gatos"}
]
export default productos;